### ISSUE TITLE
failed deletes due to file not found not counted

### ISSUE THREAD

**Issue by kevinkk525** [ReneSmeekes/storj_success_rate#7]
I have some warnings in my log that aren't counted towards the failed deletes. Is it intentional?

```
WARN    retain  failed to delete piece  {"Satellite ID": "12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs", "Piece ID": "4VPEOGTGFOMQ22KBSXWOJQ2JY6TFKKBHITYZLWY3WYG5UDNV263A", "error": "pieces error: file does not exist", "errorVerbose": "pieces error: file does not exist\n\tstorj.io/storj/storagenode/pieces.(*Store).MigrateV0ToV1:407\n\tstorj.io/storj/storagenode/pieces.(*Store).Trash:319\n\tstorj.io/storj/storagenode/retain.(*Service).retainPieces.func1:388\n\tstorj.io/storj/storagenode/storagenodedb.(*v0PieceInfoDB).WalkSatelliteV0Pieces:107\n\tstorj.io/storj/storagenode/pieces.(*Store).WalkSatellitePieces:483\n\tstorj.io/storj/storagenode/retain.(*Service).retainPieces:364\n\tstorj.io/storj/storagenode/retain.(*Service).Run.func2:220\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:57"}
```

**Comment by ReneSmeekes** [comment]
Hey @kevinkk525 ,
The delete you posted is not a regular delete, but rather garbage collection doing it's thing. This script doesn't include garbage collection actions as they are not a normal transaction between uplink and node, but rather an asynchronous clean up action by your node. You'll also note this is a warning rather than an error, because it really doesn't matter if something goes wrong with garbage collection as anything not cleaned will be cleaned again at a later point.

**Comment by kevinkk525** [comment]
yes you are right, it's just a warning and not an error. 
Ok so garbage collecting should not be counted by the script, got it. Thanks for the reply.
